# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tts_worker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tts_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10tts_worker.proto\x12\x08theo.tts\"h\n\x11SynthesizeRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05voice\x18\x03 \x01(\t\x12\x13\n\x0bsample_rate\x18\x04 \x01(\x05\x12\r\n\x05speed\x18\x05 \x01(\x02\"H\n\x0fSynthesizeChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0f\n\x07is_last\x18\x02 \x01(\x08\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\"\x0f\n\rHealthRequest\"\xaf\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x0e\n\x06\x65ngine\x18\x03 \x01(\t\x12\x38\n\x08metadata\x18\x04 \x03(\x0b\x32&.theo.tts.HealthResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x90\x01\n\tTTSWorker\x12\x46\n\nSynthesize\x12\x1b.theo.tts.SynthesizeRequest\x1a\x19.theo.tts.SynthesizeChunk0\x01\x12;\n\x06Health\x12\x17.theo.tts.HealthRequest\x1a\x18.theo.tts.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tts_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_HEALTHRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_SYNTHESIZEREQUEST']._serialized_start=30
  _globals['_SYNTHESIZEREQUEST']._serialized_end=134
  _globals['_SYNTHESIZECHUNK']._serialized_start=136
  _globals['_SYNTHESIZECHUNK']._serialized_end=208
  _globals['_HEALTHREQUEST']._serialized_start=210
  _globals['_HEALTHREQUEST']._serialized_end=225
  _globals['_HEALTHRESPONSE']._serialized_start=228
  _globals['_HEALTHRESPONSE']._serialized_end=403
  _globals['_HEALTHRESPONSE_METADATAENTRY']._serialized_start=356
  _globals['_HEALTHRESPONSE_METADATAENTRY']._serialized_end=403
  _globals['_TTSWORKER']._serialized_start=406
  _globals['_TTSWORKER']._serialized_end=550
# @@protoc_insertion_point(module_scope)
